# Generated by Django 2.0.13 on 2019-08-27 19:40

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20190314_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistartionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.PositiveIntegerField(unique=True)),
                ('whatsapp_number', models.PositiveIntegerField(unique=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.PositiveIntegerField()),
                ('father_name', models.CharField(max_length=50)),
                ('father_contact_number', models.PositiveIntegerField()),
                ('father_whatsapp_number', models.PositiveIntegerField()),
                ('mother_name', models.CharField(max_length=50)),
                ('mother_contact_number', models.PositiveIntegerField()),
                ('mother_whatsapp_number', models.PositiveIntegerField()),
                ('parent_address', models.CharField(max_length=100)),
                ('parent_city', models.CharField(max_length=50)),
                ('parent_state', models.CharField(max_length=50)),
                ('parent_pin', models.PositiveIntegerField()),
                ('school_name', models.CharField(max_length=50)),
                ('class_upto', models.CharField(max_length=50)),
                ('last_exam_percentage', models.PositiveIntegerField()),
                ('school_city', models.CharField(max_length=50)),
                ('school_state', models.CharField(max_length=50)),
                ('school_pin', models.PositiveIntegerField()),
                ('dob', models.DateField(max_length=8)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='progress',
            name='score',
            field=models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='incorrect_questions',
            field=models.CharField(blank=True, max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Incorrect questions'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='question_list',
            field=models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Question List'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='question_order',
            field=models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Question Order'),
        ),
    ]
