# Generated by Django 2.0.13 on 2019-08-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20190828_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=60)),
                ('contact_number', models.CharField(max_length=100)),
                ('whatsapp_number', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=8)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, null=True)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100)),
                ('fcontact_number', models.CharField(max_length=100)),
                ('fwhatsapp_number', models.CharField(max_length=100)),
                ('mothers_name', models.CharField(max_length=100)),
                ('mcontact_number', models.CharField(max_length=100)),
                ('mwhatsapp_number', models.CharField(max_length=100)),
                ('paddress', models.CharField(max_length=100)),
                ('pstate', models.CharField(max_length=100)),
                ('pcity', models.CharField(max_length=100)),
                ('ppin', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('class_upto', models.CharField(max_length=100)),
                ('percentage', models.CharField(max_length=100)),
                ('saddress', models.CharField(max_length=100)),
                ('sstate', models.CharField(max_length=100)),
                ('scity', models.CharField(max_length=100)),
                ('spin', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='RegistartionDetails',
        ),
    ]
